[build]
  # The command to install and build both client and server
  command = "npm install --prefix client && npm run build --prefix client && npm install --prefix server"

[start]
  # Start the backend server
  command = "node server/index.js"
